/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/core/components/ui/BaseButton.vue')['default']
    BaseHeader: typeof import('./src/core/components/ui/BaseHeader.vue')['default']
    CountDown: typeof import('./src/core/components/ui/CountDown.vue')['default']
    HorseList: typeof import('./src/modules/race/components/HorseList.vue')['default']
    HorseSilhouette: typeof import('./src/core/components/ui/HorseSilhouette.vue')['default']
    MobileNotSupported: typeof import('./src/core/components/shared/MobileNotSupported.vue')['default']
    ProgramList: typeof import('./src/modules/race/components/ProgramList.vue')['default']
    RaceTrack: typeof import('./src/modules/race/components/RaceTrack.vue')['default']
    ResultsAndProgramWrapper: typeof import('./src/modules/race/components/ResultsAndProgramWrapper.vue')['default']
    ResultsList: typeof import('./src/modules/race/components/ResultsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
